
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 378000 bytes/channel
 *	Total Size: 1 * 378000 + 4 (header) = 378044 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sharence\Documents\Fall17\CS2261\SharenceSolomero_FinalProject(M3)\GameSong.wav
 *	Time-stamp: Tue Nov 28 21:17:36 2017
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 378000

extern const unsigned char GameSong[378000];

#endif /* __GAMESONGH__ */
