
/**************************************************************
 *	
 *	GameOver, 8 bit, 11025Hz,
 *	1 channel, 28930 bytes/channel
 *	Total Size: 1 * 28930 + 4 (header) = 28974 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sharence\Documents\Fall17\CS2261\SharenceSolomero_FinalProject(M3)\GameOver.wav
 *	Time-stamp: Tue Dec 05 00:30:04 2017
 *	
 **************************************************************/

#ifndef __GAMEOVERH__
#define __GAMEOVERH__

#define GAMEOVERFREQ 11025
#define GAMEOVERLEN 28930

extern const unsigned char GameOver[28930];

#endif /* __GAMEOVERH__ */
