
/**************************************************************
 *	
 *	jump, 8 bit, 11025Hz,
 *	1 channel, 2054 bytes/channel
 *	Total Size: 1 * 2054 + 4 (header) = 2098 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sharence\Documents\Fall17\CS2261\SharenceSolomero_FinalProject(M3)\jump.wav
 *	Time-stamp: Tue Nov 28 20:25:27 2017
 *	
 **************************************************************/

#ifndef __JUMPH__
#define __JUMPH__

#define JUMPFREQ 11025
#define JUMPLEN 2054

extern const unsigned char jump[2054];

#endif /* __JUMPH__ */
